add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"
symbol = "󰘬 "

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold yellow"
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
up_to_date = ""
untracked = "?${count} "
stashed = "󰏗${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[nodejs]
format = "[$symbol($version)]($style) "
style = "bold green"
symbol = " "

[python]
format = "[$symbol($version)]($style) "
style = "bold yellow"
symbol = " "

[rust]
format = "[$symbol($version)]($style) "
style = "bold red"
symbol = " "

[golang]
format = "[$symbol($version)]($style) "
style = "bold cyan"
symbol = " "

[docker_context]
format = "[$symbol$context]($style) "
style = "bold blue"
symbol = "󰡨 "
only_with_files = true

[cmd_duration]
format = "[$duration]($style) "
style = "bold dimmed white"
min_time = 1000
